"""
mock_data.py
============
Feature : Données fictives pour les tests (mode dry-run).

Description :
    Ce module fournit un jeu de données statiques représentant des restaurants
    fictifs. Ces données sont utilisées dans les tests unitaires et le mode dry-run
    pour éviter toute consommation d'API réelle.

    Aucun appel réseau n'est effectué lors de l'import ou de l'utilisation de ce module.
    Les données couvrent des cas variés : différentes cuisines, notes, prix, distances,
    statuts d'ouverture — permettant de tester tous les filtres disponibles.

Cas d'usage :
    - Mode --dry-run : python main.py --location "Paris" --dry-run
    - Tests unitaires : import direct dans test_filters.py, test_scraper.py
    - Démo : montrer l'outil sans connexion réseau

Entrée  : Aucune (données statiques)
Sortie  : MOCK_RESTAURANTS — List[dict] de restaurants au format standardisé
"""

# Point de référence : centre de Paris (Tour Eiffel)
MOCK_REFERENCE_LAT = 48.8584
MOCK_REFERENCE_LNG = 2.2945

MOCK_RESTAURANTS: list[dict] = [
    {
        "id": "mock_001",
        "name": "Trattoria Roma",
        "address": "12 Rue de Rivoli, 75001 Paris",
        "latitude": 48.8601,
        "longitude": 2.2978,
        "rating": 4.6,
        "price_level": 2,
        "cuisine": "italian",
        "is_open_now": True,
        "distance_m": 320.0,
        "phone": "+33 1 42 36 12 00",
        "website": "https://trattoriaroma.example.com",
        "source": "mock",
    },
    {
        "id": "mock_002",
        "name": "Sakura Sushi",
        "address": "45 Avenue de la Bourdonnais, 75007 Paris",
        "latitude": 48.8551,
        "longitude": 2.3012,
        "rating": 4.4,
        "price_level": 3,
        "cuisine": "japanese",
        "is_open_now": True,
        "distance_m": 780.0,
        "phone": "+33 1 45 55 78 00",
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_003",
        "name": "Le Petit Bistrot",
        "address": "8 Rue Saint-Dominique, 75007 Paris",
        "latitude": 48.8565,
        "longitude": 2.3089,
        "rating": 4.1,
        "price_level": 2,
        "cuisine": "french",
        "is_open_now": False,
        "distance_m": 450.0,
        "phone": "+33 1 47 05 49 75",
        "website": "https://lepetitbistrot.example.com",
        "source": "mock",
    },
    {
        "id": "mock_004",
        "name": "Dragon d'Or",
        "address": "23 Rue de la Paix, 75002 Paris",
        "latitude": 48.8697,
        "longitude": 2.3309,
        "rating": 3.8,
        "price_level": 1,
        "cuisine": "chinese",
        "is_open_now": True,
        "distance_m": 1500.0,
        "phone": None,
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_005",
        "name": "Spice Garden",
        "address": "67 Rue Monge, 75005 Paris",
        "latitude": 48.8481,
        "longitude": 2.3519,
        "rating": 4.3,
        "price_level": 2,
        "cuisine": "indian",
        "is_open_now": True,
        "distance_m": 890.0,
        "phone": "+33 1 43 31 12 34",
        "website": "https://spicegarden.example.com",
        "source": "mock",
    },
    {
        "id": "mock_006",
        "name": "Casa Mexico",
        "address": "34 Boulevard Saint-Germain, 75006 Paris",
        "latitude": 48.8534,
        "longitude": 2.3413,
        "rating": 3.9,
        "price_level": 2,
        "cuisine": "mexican",
        "is_open_now": False,
        "distance_m": 650.0,
        "phone": "+33 1 43 54 00 00",
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_007",
        "name": "Le Grand Luxe",
        "address": "1 Place Vendome, 75001 Paris",
        "latitude": 48.8672,
        "longitude": 2.3295,
        "rating": 4.8,
        "price_level": 4,
        "cuisine": "french",
        "is_open_now": True,
        "distance_m": 1200.0,
        "phone": "+33 1 43 16 30 30",
        "website": "https://legrandluxe.example.com",
        "source": "mock",
    },
    {
        "id": "mock_008",
        "name": "Thai Orchid",
        "address": "89 Rue de Courcelles, 75008 Paris",
        "latitude": 48.8762,
        "longitude": 2.3061,
        "rating": 4.2,
        "price_level": 2,
        "cuisine": "thai",
        "is_open_now": True,
        "distance_m": 970.0,
        "phone": "+33 1 42 27 00 00",
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_009",
        "name": "Burger Republic",
        "address": "15 Rue de Turbigo, 75003 Paris",
        "latitude": 48.8631,
        "longitude": 2.3526,
        "rating": 3.5,
        "price_level": 1,
        "cuisine": "burger",
        "is_open_now": True,
        "distance_m": 400.0,
        "phone": None,
        "website": "https://burgerrepublic.example.com",
        "source": "mock",
    },
    {
        "id": "mock_010",
        "name": "La Taverna Toscana",
        "address": "56 Rue du Temple, 75004 Paris",
        "latitude": 48.8598,
        "longitude": 2.3541,
        "rating": 4.5,
        "price_level": 3,
        "cuisine": "italian",
        "is_open_now": None,  # Statut inconnu
        "distance_m": 550.0,
        "phone": "+33 1 42 72 00 00",
        "website": "https://latavernatoscana.example.com",
        "source": "mock",
    },
    {
        "id": "mock_011",
        "name": "Seoul Kitchen",
        "address": "28 Rue des Ecoles, 75005 Paris",
        "latitude": 48.8507,
        "longitude": 2.3483,
        "rating": 4.0,
        "price_level": 2,
        "cuisine": "korean",
        "is_open_now": True,
        "distance_m": 730.0,
        "phone": "+33 1 43 26 00 00",
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_012",
        "name": "Chez Marcel",
        "address": "3 Rue Mouffetard, 75005 Paris",
        "latitude": 48.8433,
        "longitude": 2.3505,
        "rating": None,  # Pas de note
        "price_level": 1,
        "cuisine": "french",
        "is_open_now": True,
        "distance_m": 850.0,
        "phone": "+33 1 43 31 00 00",
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_013",
        "name": "Mediterranean Dream",
        "address": "42 Quai des Orfevres, 75001 Paris",
        "latitude": 48.8561,
        "longitude": 2.3467,
        "rating": 4.7,
        "price_level": 3,
        "cuisine": "mediterranean",
        "is_open_now": True,
        "distance_m": 180.0,
        "phone": "+33 1 43 54 00 00",
        "website": "https://mediterraneandream.example.com",
        "source": "mock",
    },
    {
        "id": "mock_014",
        "name": "Pho Saigon",
        "address": "71 Rue de Tolbiac, 75013 Paris",
        "latitude": 48.8287,
        "longitude": 2.3562,
        "rating": 4.1,
        "price_level": 1,
        "cuisine": "vietnamese",
        "is_open_now": False,
        "distance_m": 2100.0,  # Hors rayon 2km
        "phone": None,
        "website": None,
        "source": "mock",
    },
    {
        "id": "mock_015",
        "name": "The Green Bowl",
        "address": "19 Rue Saint-Martin, 75004 Paris",
        "latitude": 48.8602,
        "longitude": 2.3501,
        "rating": 4.3,
        "price_level": 2,
        "cuisine": "vegan",
        "is_open_now": True,
        "distance_m": 520.0,
        "phone": "+33 1 42 71 00 00",
        "website": "https://thegreenbowl.example.com",
        "source": "mock",
    },
]
